---
title: "1.hpc_fig1.Rmd"
output: html_document
date: "2025-06-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(data.table)
library(future.apply)
library(dplyr)
library(ggplot2)
library(ggsignif)
library(cowplot)
# Set up parallelization
future::plan(multisession)
```

```{r}
final_df <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_results/clinvar_all_protein_filtered_with_esm1v_dec2025_filtered.csv")
nrow(final_df)

total_patho <- final_df %>%
  dplyr::filter(clinvar_clinical_significance %in% c("pathogenic", "likely_pathogenic"))
nrow(total_patho) #32147

total_benign <- final_df %>%
  dplyr::filter(clinvar_clinical_significance %in% c("benign", "likely_benign"))
nrow(total_benign) #69909

final_df <- final_df %>%
  mutate(stability = case_when(
    ddG_pred > 1 ~ "destabilizing",
    ddG_pred < -0.5 ~ "stabilizing",
    TRUE ~ "WT-like"  # Default case
  ))

# Summarize data by categories and pathogenicity
final_summary_df <- final_df %>%
  mutate(clinvar_clinical_significance = case_when(
    clinvar_clinical_significance %in% c("likely_benign", "benign") ~ "benign",
    clinvar_clinical_significance %in% c("likely_pathogenic", "pathogenic") ~ "pathogenic",
    TRUE ~ clinvar_clinical_significance  # Keep other categories unchanged
  )) %>%
  # Group by the new clinical significance categories and stability
  group_by(clinvar_clinical_significance, stability) %>%
  summarise(count = n(), .groups = "drop") %>%
  # Recalculate percentages after merging
  group_by(clinvar_clinical_significance) %>%
  mutate(percent = (count / sum(count)) * 100) %>%
  ungroup()

final_summary_df
```
```{r}
# Creating a contingency table
final_contingency_table <- matrix(c(
  final_summary_df$count[final_summary_df$clinvar_clinical_significance == "pathogenic" & final_summary_df$stability == "destabilizing"], 
  final_summary_df$count[final_summary_df$clinvar_clinical_significance == "benign" & final_summary_df$stability == "destabilizing"],
  sum(final_summary_df$count[final_summary_df$clinvar_clinical_significance == "pathogenic" & final_summary_df$stability != "destabilizing"]),
  sum(final_summary_df$count[final_summary_df$clinvar_clinical_significance == "benign" & final_summary_df$stability != "destabilizing"])
), nrow = 2, byrow = TRUE)

# Adding row and column names for clarity
colnames(final_contingency_table) <- c("Pathogenic", "Benign")
rownames(final_contingency_table) <- c("Destabilizing", "Non-Destabilizing")

# Displaying the table
print(final_contingency_table)
```

```{r}
# library(pROC)
# library(PRROC)
# 
# # Create expanded binary vectors
# y_true <- c(
#   rep(1, 15554),  # pathogenic destabilizing
#   rep(1, 16593),  # pathogenic non-destabilizing
#   rep(0, 6129),   # benign destabilizing
#   rep(0, 63780)   # benign non-destabilizing
# )
# 
# # Predicted labels or scores: 1 for destabilizing, 0 for not
# y_pred <- c(
#   rep(1, 15554),  # pathogenic destabilizing
#   rep(0, 16593),  # pathogenic non-destabilizing
#   rep(1, 6129),   # benign destabilizing
#   rep(0, 63780)   # benign non-destabilizing
# )
# 
# # ROC AUC
# roc_obj <- roc(y_true, y_pred)
# roc_auc <- auc(roc_obj)
# 
# # PR AUC
# pr_obj <- pr.curve(scores.class0 = y_pred[y_true == 1],
#                    scores.class1 = y_pred[y_true == 0],
#                    curve = TRUE)
# pr_auc <- pr_obj$auc.integral
# 
# # Print results
# cat("ROC-AUC:", round(roc_auc, 4), "\n")
# #ROC-AUC: 0.6981
# cat("PR-AUC:", round(pr_auc, 4), "\n")
# #PR-AUC: 0.5638 
```


```{r}
# Calculate the Odds Ratio using Fisher's Test
final_result <- fisher.test(final_contingency_table)
final_result
```
```{r}
final_summary_df$stability <- factor(final_summary_df$stability, levels = c("WT-like", "destabilizing", "stabilizing"))
final_summary_df$clinvar_clinical_significance <- factor(final_summary_df$clinvar_clinical_significance, levels = c("benign", "pathogenic"))

nrow(final_df) # 102056
length(unique(final_df$uniprot)) #12114
```

```{r, fig.width=5, fig.height=6}
p1 <- ggplot(
  final_summary_df,
  aes(x = clinvar_clinical_significance, y = percent, fill = stability)
) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +
  geom_text(
    aes(label = paste0(round(percent, 1), "% (", count, ")")),
    position = position_stack(vjust = 0.5),
    size = 6.5
  ) +
  scale_fill_manual(
    values = c(
      "stabilizing"      = "#8DA0CB",  
      "WT-like"         = "#C9CED3",  # mid grey
      "destabilizing" = "#8F98A1"   # darker grey / blue-grey
    )
  ) +
  labs(
    title = "All Variants",
    subtitle = "102,056 ClinVar Variants",
    x = NULL,
    y = "Variant percentage (%)",
    fill = NULL
  ) +
  theme_classic() +
  ylim(0, 100) +
  theme(
    legend.position = "bottom",
    plot.title = element_text(size = 24, hjust = 0, face = "bold"),
    plot.subtitle = element_text(size = 22, hjust = 0),
    axis.text.y = element_text(size = 20),
    axis.text.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_text(size = 20),
    legend.key.size = unit(1.2, "cm")
  )

p1
```

```{r}
core_df <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_results/clinvar_all_protein_filtered_with_esm1v_core_dec2025.csv")
nrow(core_df) #25357

core_total_patho <- core_df %>%
  dplyr::filter(clinvar_clinical_significance %in% c("pathogenic", "likely_pathogenic"))
nrow(core_total_patho) #15907

core_total_benign <- core_df %>%
  dplyr::filter(clinvar_clinical_significance %in% c("benign", "likely_benign"))
nrow(core_total_benign) #9450

core_df <- core_df %>%
  mutate(stability = case_when(
    ddG_pred > 1 ~ "destabilizing",
    ddG_pred < -0.5 ~ "stabilizing",
    TRUE ~ "WT-like"  # Default case
  ))

# Summarize data by categories and pathogenicity
core_summary_df <- core_df %>%
  mutate(clinvar_clinical_significance = case_when(
    clinvar_clinical_significance %in% c("likely_benign", "benign") ~ "benign",
    clinvar_clinical_significance %in% c("likely_pathogenic", "pathogenic") ~ "pathogenic",
    TRUE ~ clinvar_clinical_significance  # Keep other categories unchanged
  )) %>%
  # Group by the new clinical significance categories and stability
  group_by(clinvar_clinical_significance, stability) %>%
  summarise(count = n(), .groups = "drop") %>%
  # Recalculate percentages after merging
  group_by(clinvar_clinical_significance) %>%
  mutate(percent = (count / sum(count)) * 100) %>%
  ungroup()

core_summary_df
```
```{r}
# Set factor levels for consistent ordering
core_summary_df$stability <- factor(core_summary_df$stability, levels = c("WT-like", "destabilizing", "stabilizing"))
core_summary_df$clinvar_clinical_significance <- factor(core_summary_df$clinvar_clinical_significance, levels = c("benign", "pathogenic"))

nrow(core_df) #25357
length(unique(core_df$uniprot)) #4870
```

```{r}
# Creating a contingency table
core_contingency_table <- matrix(c(
  core_summary_df$count[core_summary_df$clinvar_clinical_significance == "pathogenic" & core_summary_df$stability == "destabilizing"], 
  core_summary_df$count[core_summary_df$clinvar_clinical_significance == "benign" & core_summary_df$stability == "destabilizing"],
  sum(core_summary_df$count[core_summary_df$clinvar_clinical_significance == "pathogenic" & core_summary_df$stability != "destabilizing"]),
  sum(core_summary_df$count[core_summary_df$clinvar_clinical_significance == "benign" & core_summary_df$stability != "destabilizing"])
), nrow = 2, byrow = TRUE)

# Adding row and column names for clarity
colnames(core_contingency_table) <- c("Pathogenic", "Benign")
rownames(core_contingency_table) <- c("Destabilizing", "Non-Destabilizing")

# Displaying the table
print(core_contingency_table)
```

```{r}
# Calculate the Odds Ratio using Fisher's Test
core_result <- fisher.test(core_contingency_table)
core_result
```

```{r, fig.width=5, fig.height=6}
p2 <- ggplot(core_summary_df, aes(x = clinvar_clinical_significance, y = percent, fill = stability)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +  # Stacked bars
  geom_text(aes(label = paste0(round(percent, 1), "% (", count, ")")), 
            position = position_stack(vjust = 0.5), size = 6.5) +  # Center labels in stacks
  scale_fill_manual(
    values = c(
      "stabilizing"      = "#8DA0CB",  
      "WT-like"         = "#C9CED3",  # mid grey
      "destabilizing" = "#8F98A1"   # darker grey / blue-grey
    )
  ) +
  labs(title = "Core variants", subtitle = "25,357 ClinVar Variants",
       x = NULL, y = "Variant percentage (%)", fill = NULL) +
  theme_classic() + ylim(0, 100) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 24, hjust = 0, face = "bold"),
        plot.subtitle = element_text(size = 22, hjust = 0),
        axis.text.y = element_text(size = 20) ,
        axis.text.x = element_text(size = 20) ,
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),       # Increase legend text size
        legend.title = element_text(size = 20),      # Increase legend title size
        legend.key.size = unit(1.2, "cm"))            # Increase legend box size

p2
```
```{r, fig.width=10, fig.height=6}
p3 <- plot_grid(p1,p2, ncol=2)

ggsave("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/figs/revision/fig1_clinvar.pdf", plot = p3, width = 12, height = 7, dpi = 500)

p3
```
```{r}
bi_df <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_inputs/pioneer_interactome/all_bi_residues.csv")

nrow(final_df) #102056
final_df2 <- merge(final_df, bi_df, by = "uniprot", all.x = TRUE)
nrow(final_df2) #102056

final_df2 <- final_df2 %>%
  mutate(
    interface_list = str_split(coalesce(interface_residues, ""), ",\\s*"),
    interface_list = map(interface_list, ~ suppressWarnings(as.integer(.x))),
    is_interface = map2_lgl(new_position, interface_list, ~ .x %in% .y)
  )

final_df2 <- final_df2 %>%
  mutate(
    is_core_strict = if_else(
      !is.na(exposure_rasa) & !is.na(spot_disorder) & !is.na(is_interface) &
        (exposure_rasa <= 0.2) & (spot_disorder == 0) & (!is_interface),
      TRUE, FALSE)
  )

table(final_df2$is_core_strict, useNA = "ifany")
```

```{r}
df_for_test <- final_df2 %>%
  filter(!is.na(ddG_pred)) %>%
  mutate(
    core_class = if_else(is_core_strict, "Core", "NonCore"),
    destab_class = if_else(stability == "destabilizing", "Destabilizing", "NonDestabilizing")
  )

contingency_table <- table(df_for_test$core_class, df_for_test$destab_class)
contingency_table

fisher.test(contingency_table)
```
```{r}
df_for_test2 <- final_df2 %>%
  mutate(
    core_class = if_else(is_core_strict, "Core", "NonCore"),
    destab_class = if_else(clinvar_clinical_significance  %in% c("likely_pathogenic", "pathogenic"), "Pathogenic", "Benign")
  )

df_for_test2$destab_class <- factor(df_for_test2$destab_class, levels = c("Pathogenic", "Benign"))

contingency_table <- table(df_for_test2$core_class, df_for_test2$destab_class)
contingency_table

fisher.test(contingency_table)
```


```{r}
final_df_three_star <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_results/clinvar_all_protein_filtered_with_esm1v_new_at_least_one_three_star.csv")
nrow(final_df_three_star) #1974

final_df_three_star_total_patho <- final_df_three_star %>%
  dplyr::filter(clinvar_clinical_significance %in% c("pathogenic", "likely_pathogenic"))
nrow(final_df_three_star_total_patho) #1348

final_df_three_star_total_benign <- final_df_three_star %>%
  dplyr::filter(clinvar_clinical_significance %in% c("benign", "likely_benign"))
nrow(final_df_three_star_total_benign) #626

final_df_three_star <- final_df_three_star %>%
  mutate(stability = case_when(
    ddG_pred > 1 ~ "destabilizing",
    ddG_pred < -0.5 ~ "stabilizing",
    TRUE ~ "WT-like"  # Default case
  ))

# Summarize data by categories and pathogenicity
final_df_three_star_summary_df <- final_df_three_star %>%
  mutate(clinvar_clinical_significance = case_when(
    clinvar_clinical_significance %in% c("likely_benign", "benign") ~ "benign",
    clinvar_clinical_significance %in% c("likely_pathogenic", "pathogenic") ~ "pathogenic",
    TRUE ~ clinvar_clinical_significance  # Keep other categories unchanged
  )) %>%
  # Group by the new clinical significance categories and stability
  group_by(clinvar_clinical_significance, stability) %>%
  summarise(count = n(), .groups = "drop") %>%
  # Recalculate percentages after merging
  group_by(clinvar_clinical_significance) %>%
  mutate(percent = (count / sum(count)) * 100) %>%
  ungroup()

final_df_three_star_summary_df
```
```{r}
# Set factor levels for consistent ordering
final_df_three_star_summary_df$stability <- factor(final_df_three_star_summary_df$stability, levels = c("WT-like", "destabilizing", "stabilizing"))
final_df_three_star_summary_df$clinvar_clinical_significance <- factor(final_df_three_star_summary_df$clinvar_clinical_significance, levels = c("benign", "pathogenic"))

nrow(final_df_three_star) #1974
length(unique(final_df_three_star$uniprot)) #57
```

```{r, fig.width=5, fig.height=6}
p4 <- ggplot(final_df_three_star_summary_df, aes(x = clinvar_clinical_significance, y = percent, fill = stability)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +  # Stacked bars
  geom_text(aes(label = paste0(round(percent, 1), "% (", count, ")")), 
            position = position_stack(vjust = 0.5), size = 6.5) +  # Center labels in stacks
  scale_fill_manual(
    values = c(
      "stabilizing"      = "#8DA0CB",  
      "WT-like"         = "#C9CED3",  # mid grey
      "destabilizing" = "#8F98A1"   # darker grey / blue-grey
    )
  ) +
  labs(title = "3-star variants", subtitle = "1974 ClinVar Variants",
       x = NULL, y = "Variant percentage (%)", fill = NULL) +
  theme_classic() + ylim(0, 100) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 24, hjust = 0, face = "bold"),
        plot.subtitle = element_text(size = 22, hjust = 0),
        axis.text.y = element_text(size = 20) ,
        axis.text.x = element_text(size = 20) ,
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),       # Increase legend text size
        legend.title = element_text(size = 20),      # Increase legend title size
        legend.key.size = unit(1.2, "cm"))            # Increase legend box size

p4
```
```{r}
core_df_three_star <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_results/clinvar_all_protein_filtered_with_esm1v_core_threestar_dec2025.csv")
nrow(core_df_three_star) #879

core_df_three_star_total_patho <- core_df_three_star %>%
  dplyr::filter(clinvar_clinical_significance %in% c("pathogenic", "likely_pathogenic"))
nrow(core_df_three_star_total_patho) #797

core_df_three_star_total_benign <- core_df_three_star %>%
  dplyr::filter(clinvar_clinical_significance %in% c("benign", "likely_benign"))
nrow(core_df_three_star_total_benign) #82

core_df_three_star <- core_df_three_star %>%
  mutate(stability = case_when(
    ddG_pred > 1 ~ "destabilizing",
    ddG_pred < -0.5 ~ "stabilizing",
    TRUE ~ "WT-like"  # Default case
  ))

# Summarize data by categories and pathogenicity
core_df_three_star_summary_df <- core_df_three_star %>%
  mutate(clinvar_clinical_significance = case_when(
    clinvar_clinical_significance %in% c("likely_benign", "benign") ~ "benign",
    clinvar_clinical_significance %in% c("likely_pathogenic", "pathogenic") ~ "pathogenic",
    TRUE ~ clinvar_clinical_significance  # Keep other categories unchanged
  )) %>%
  # Group by the new clinical significance categories and stability
  group_by(clinvar_clinical_significance, stability) %>%
  summarise(count = n(), .groups = "drop") %>%
  # Recalculate percentages after merging
  group_by(clinvar_clinical_significance) %>%
  mutate(percent = (count / sum(count)) * 100) %>%
  ungroup()

core_df_three_star_summary_df
```
```{r}
# Set factor levels for consistent ordering
core_df_three_star_summary_df$stability <- factor(core_df_three_star_summary_df$stability, levels = c("WT-like", "destabilizing", "stabilizing"))
core_df_three_star_summary_df$clinvar_clinical_significance <- factor(core_df_three_star_summary_df$clinvar_clinical_significance, levels = c("benign", "pathogenic"))

nrow(core_df_three_star) #879
length(unique(core_df_three_star$uniprot)) #44
```
```{r, fig.width=5, fig.height=6}
p5 <- ggplot(core_df_three_star_summary_df, aes(x = clinvar_clinical_significance, y = percent, fill = stability)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +  # Stacked bars
  geom_text(aes(label = paste0(round(percent, 1), "% (", count, ")")), 
            position = position_stack(vjust = 0.5), size = 6.5) +  # Center labels in stacks
  scale_fill_manual(
    values = c(
      "stabilizing"      = "#8DA0CB",  
      "WT-like"         = "#C9CED3",  # mid grey
      "destabilizing" = "#8F98A1"   # darker grey / blue-grey
    )
  ) +
  labs(title = "3-star Core Variants", subtitle = "879 ClinVar Variants",
       x = NULL, y = "Variant percentage (%)", fill = NULL) +
  theme_classic() + ylim(0, 100) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 24, hjust = 0, face = "bold"),
        plot.subtitle = element_text(size = 22, hjust = 0),
        axis.text.y = element_text(size = 20) ,
        axis.text.x = element_text(size = 20) ,
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),       # Increase legend text size
        legend.title = element_text(size = 20),      # Increase legend title size
        legend.key.size = unit(1.2, "cm"))            # Increase legend box size

p5
```
```{r, fig.width=10, fig.height=6}
p6 <- plot_grid(p4,p5, ncol=2)
ggsave("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/figs/revision/fig1_clinvar_threestar.pdf", plot = p6, width = 10, height = 6, dpi = 500)
p6
```

```{r}
nrow(final_df) #102056
nrow(final_df %>% filter (exposure_plddt < 70))  #39709
nrow(final_df %>% filter (exposure_plddt < 70)) / nrow(final_df) #0.3890903

conf_final_df <- final_df %>% filter (exposure_plddt >= 70)
nrow(conf_final_df) #62347

conf_total_patho <- conf_final_df %>%
  dplyr::filter(clinvar_clinical_significance %in% c("pathogenic", "likely_pathogenic"))
nrow(conf_total_patho) #27731

conf_total_benign <- conf_final_df %>%
  dplyr::filter(clinvar_clinical_significance %in% c("benign", "likely_benign"))
nrow(conf_total_benign) #34616

conf_final_df <- conf_final_df %>%
  mutate(stability = case_when(
    ddG_pred > 1 ~ "destabilizing",
    ddG_pred < -0.5 ~ "stabilizing",
    TRUE ~ "WT-like"  # Default case
  ))

# Summarize data by categories and pathogenicity
conf_summary_df <- conf_final_df %>%
  mutate(clinvar_clinical_significance = case_when(
    clinvar_clinical_significance %in% c("likely_benign", "benign") ~ "benign",
    clinvar_clinical_significance %in% c("likely_pathogenic", "pathogenic") ~ "pathogenic",
    TRUE ~ clinvar_clinical_significance  # Keep other categories unchanged
  )) %>%
  # Group by the new clinical significance categories and stability
  group_by(clinvar_clinical_significance, stability) %>%
  summarise(count = n(), .groups = "drop") %>%
  # Recalculate percentages after merging
  group_by(clinvar_clinical_significance) %>%
  mutate(percent = (count / sum(count)) * 100) %>%
  ungroup()

conf_summary_df
```
```{r}
# Creating a contingency table
conf_contingency_table <- matrix(c(
  conf_summary_df$count[conf_summary_df$clinvar_clinical_significance == "pathogenic" & conf_summary_df$stability == "destabilizing"], 
  conf_summary_df$count[conf_summary_df$clinvar_clinical_significance == "benign" & conf_summary_df$stability == "destabilizing"],
  sum(conf_summary_df$count[conf_summary_df$clinvar_clinical_significance == "pathogenic" & conf_summary_df$stability != "destabilizing"]),
  sum(conf_summary_df$count[conf_summary_df$clinvar_clinical_significance == "benign" & conf_summary_df$stability != "destabilizing"])
), nrow = 2, byrow = TRUE)

# Adding row and column names for clarity
colnames(conf_contingency_table) <- c("Pathogenic", "Benign")
rownames(conf_contingency_table) <- c("Destabilizing", "Non-Destabilizing")

# Displaying the table
print(conf_contingency_table)
```


```{r}
# Calculate the Odds Ratio using Fisher's Test
conf_result <- fisher.test(conf_contingency_table)
print(conf_result$estimate)  
```

```{r}
conf_summary_df$stability <- factor(conf_summary_df$stability, levels = c("WT-like", "destabilizing", "stabilizing"))
conf_summary_df$clinvar_clinical_significance <- factor(conf_summary_df$clinvar_clinical_significance, levels = c("benign", "pathogenic"))

nrow(conf_final_df) # 62347
length(unique(conf_final_df$uniprot)) #9267
```
```{r, fig.width=6, fig.height=7}
p7 <- ggplot(conf_summary_df, aes(x = clinvar_clinical_significance, y = percent, fill = stability)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +  # Stacked bars
  geom_text(aes(label = paste0(round(percent, 1), "% (", count, ")")), 
            position = position_stack(vjust = 0.5), size = 6.5) +  # Center labels in stacks
  scale_fill_manual(
    values = c(
      "stabilizing"      = "#8DA0CB",  
      "WT-like"         = "#C9CED3",  # mid grey
      "destabilizing" = "#8F98A1"   # darker grey / blue-grey
    )
  ) +
  labs(title = "All variants with pLDDT > 70", subtitle = "62,347 ClinVar Variants",
       x = NULL, y = "Variant percentage (%)", fill = NULL) +
  theme_classic() + ylim(0, 100) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 24, hjust = 0, face = "bold"),
        plot.subtitle = element_text(size = 22, hjust = 0),
        axis.text.y = element_text(size = 20) ,
        axis.text.x = element_text(size = 20) ,
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),       # Increase legend text size
        legend.title = element_text(size = 20),      # Increase legend title size
        legend.key.size = unit(1.2, "cm"))            # Increase legend box size
p7
```

```{r}
bi_df <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_inputs/pioneer_interactome/all_bi_residues.csv")

conf_core_df <- merge(conf_final_df, bi_df, by = "uniprot", all.x = TRUE)
nrow(conf_core_df) #62347

conf_core_df <- conf_core_df %>% filter (exposure_rasa <= 0.2) %>% filter (spot_disorder == 0)

# Step 1: Convert interface_residues to a list of numeric values
conf_core_df <- conf_core_df %>%
  mutate(
    interface_residues = str_split(interface_residues, ",\\s*"), # Split into individual residues
    interface_residues = lapply(interface_residues, as.numeric) # Convert to numeric
  )

# Step 2: Filter rows where new_position is not in interface_residues
conf_core_df <- conf_core_df %>%
  rowwise() %>%
  filter(!(new_position %in% interface_residues)) %>%
  ungroup()

conf_core_df <- conf_core_df %>%
  mutate(interface_residues = sapply(interface_residues, function(x) paste(x, collapse = ",")))

nrow(clinvar_core_fil) #24931

conf_core_summary_df <- conf_core_df %>%
  mutate(clinvar_clinical_significance = case_when(
    clinvar_clinical_significance %in% c("likely_benign", "benign") ~ "benign",
    clinvar_clinical_significance %in% c("likely_pathogenic", "pathogenic") ~ "pathogenic",
    TRUE ~ clinvar_clinical_significance  # Keep other categories unchanged
  )) %>%
  # Group by the new clinical significance categories and stability
  group_by(clinvar_clinical_significance, stability) %>%
  summarise(count = n(), .groups = "drop") %>%
  # Recalculate percentages after merging
  group_by(clinvar_clinical_significance) %>%
  mutate(percent = (count / sum(count)) * 100) %>%
  ungroup()

conf_core_summary_df
```
```{r}
# Calculate the Odds Ratio using Fisher's Test
conf_core_result <- fisher.test(conf_core_contingency_table)
print(conf_core_result$estimate)  
```

```{r}
conf_core_summary_df$stability <- factor(conf_core_summary_df$stability, levels = c("WT-like", "destabilizing", "stabilizing"))
conf_core_summary_df$clinvar_clinical_significance <- factor(conf_core_summary_df$clinvar_clinical_significance, levels = c("benign", "pathogenic"))

nrow(conf_core_df) # 24931
length(unique(conf_core_df$uniprot)) #4803
```

```{r}
# Creating a contingency table
conf_core_contingency_table <- matrix(c(
  conf_core_summary_df$count[conf_core_summary_df$clinvar_clinical_significance == "pathogenic" & conf_core_summary_df$stability == "destabilizing"], 
  conf_core_summary_df$count[conf_core_summary_df$clinvar_clinical_significance == "benign" & conf_core_summary_df$stability == "destabilizing"],
  sum(conf_core_summary_df$count[conf_core_summary_df$clinvar_clinical_significance == "pathogenic" & conf_core_summary_df$stability != "destabilizing"]),
  sum(conf_core_summary_df$count[conf_core_summary_df$clinvar_clinical_significance == "benign" & conf_core_summary_df$stability != "destabilizing"])
), nrow = 2, byrow = TRUE)

# Adding row and column names for clarity
colnames(conf_core_contingency_table) <- c("Pathogenic", "Benign")
rownames(conf_core_contingency_table) <- c("Destabilizing", "Non-Destabilizing")

# Displaying the table
print(conf_core_contingency_table)
```
```{r, fig.width=6, fig.height=7}
p8 <- ggplot(conf_core_summary_df, aes(x = clinvar_clinical_significance, y = percent, fill = stability)) +
  geom_bar(stat = "identity", position = "stack", width = 0.7) +  # Stacked bars
  geom_text(aes(label = paste0(round(percent, 1), "% (", count, ")")), 
            position = position_stack(vjust = 0.5), size = 6.5) +  # Center labels in stacks
  scale_fill_manual(
    values = c(
      "stabilizing"      = "#8DA0CB",  
      "WT-like"         = "#C9CED3",  # mid grey
      "destabilizing" = "#8F98A1"   # darker grey / blue-grey
    )
  ) +
  labs(title = "Core variants with pLDDT > 70", subtitle = "24,931 ClinVar Variants",
       x = NULL, y = "Variant percentage (%)", fill = NULL) +
  theme_classic() + ylim(0, 105) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 24, hjust = 0, face = "bold"),
        plot.subtitle = element_text(size = 22, hjust = 0),
        axis.text.y = element_text(size = 20) ,
        axis.text.x = element_text(size = 20) ,
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),       # Increase legend text size
        legend.title = element_text(size = 20),      # Increase legend title size
        legend.key.size = unit(1.2, "cm"))            # Increase legend box size
p8
```
```{r, fig.width=10, fig.height=6}
p9 <- plot_grid(p7,p8, ncol=2)
ggsave("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/figs/revision/fig1_clinvar_plddt70.pdf", plot = p9, width = 10, height = 6, dpi = 500)
p9
```


```{r}
all_var_r2 <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_results/all_var_esm1v_lm_r2_jan2026.csv")
nrow(all_var_r2)
all_var_r2 <- all_var_r2 %>% filter(!is.na(adj_r2))
nrow(all_var_r2) #19288
median(all_var_r2$adj_r2, na.rm = TRUE) #0.2240873

IQR(all_var_r2$adj_r2, na.rm = FALSE) #0.1726233
quantile(all_var_r2$adj_r2, 0.25, na.rm = FALSE) #0.1252905 
quantile(all_var_r2$adj_r2, 0.75, na.rm = FALSE) #0.2979138

core_var_r2 <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/data/proteome_meta/core_lm_r2.csv")
nrow(core_var_r2) #17420
sum(!is.na(core_var_r2$adj_r2)) #17420
median(core_var_r2$adj_r2, na.rm = TRUE) #0.1581737

IQR(core_var_r2$adj_r2, na.rm = FALSE) #0.1356202
quantile(core_var_r2$adj_r2, 0.25, na.rm = FALSE) #0.09595388
quantile(core_var_r2$adj_r2, 0.75, na.rm = FALSE) #0.2315741 

```

```{r}
# # Use multiple sessions (parallel workers)
# plan(multisession)
# 
# # Set the directory path where your RDS files are stored
# dir_path <- "/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/00.human_proteome_results/lm_rds_jan2026"
# 
# # List all RDS files in the directory
# rds_files <- list.files(path = dir_path, pattern = "\\_lm.rds$", full.names = TRUE)
# 
# safe_read_and_count <- safely(function(file) {
#   lm_rds <- readRDS(file)
#   if (!is.null(lm_rds$predicted_data)) {
#     sum(rowSums(!is.na(lm_rds$predicted_data)) > 0)
#   } else {
#     0
#   }
# })
# 
# results <- future_map(rds_files, safe_read_and_count)
# 
# # Extract row counts (default to 0 if error)
# row_counts <- map_int(results, ~ if (is.null(.x$error)) .x$result else 0)
# sum(row_counts)
# # 187634329

# # Use multiple sessions (parallel workers)
# future::plan(multisession)
# 
# # Set the directory path where your RDS files are stored
# core_dir_path <- "/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/00.human_proteome_results/core_lm_rds"
# 
# # List all RDS files in the directory
# core_rds_files <- list.files(path = core_dir_path, pattern = "\\_lm.rds", full.names = TRUE)
# length(core_rds_files) #17420
# 
# #nrow(readRDS(rds_files[1])$predicted_data)
# #sum(rowSums(!is.na(readRDS(rds_files[1])$predicted_data)) > 0)
# core_results <- future_map(core_rds_files, safe_read_and_count)
# 
# # Extract row counts (default to 0 if error)
# core_row_counts <- map_int(core_results, ~ if (is.null(.x$error)) .x$result else 0)
# 
# # Identify files with errors
# core_error_files <- rds_files[which(!map_lgl(core_results, ~ is.null(.x$error)))]
# 
# core_error_files
# #character(0)
# # Sum up the total rows
# core_total_rows <- sum(core_row_counts)
# 
# # Print the result
# cat("Total number of rows in predicted_data across all RDS files:", core_total_rows, "\n")
# #Total number of rows in predicted_data across all RDS files: 47841329 
```


```{r, fig.width=5, fig.height=4}
r2_combined <- bind_rows(
  all_var_r2 %>% mutate(source = "All"),
  core_var_r2 %>% mutate(source = "Core")
)
#min(all_var_r2$adj_r2) #-0.004163465

# Count summaries
n_all <- length(unique(all_var_r2$protein_id))
n_var_all <- 187634329

n_core <- length(unique(core_var_r2$protein_id))
n_var_core <- 47841329

# Median R²s
med_all <- median(all_var_r2$adj_r2, na.rm = TRUE) #0.2243766
med_core <- median(core_var_r2$adj_r2) #0.1581737

# Rename column to standardize
r2_combined <- r2_combined  %>%
  mutate(source = factor(source, levels = c("All", "Core")))

# Plot
p10 <- ggplot(r2_combined, aes(x = source, y = adj_r2, fill = source)) +
  geom_violin(trim = FALSE, color = NA, alpha = 0.7) +
  geom_boxplot(width = 0.5, outlier.shape = NA, color = "grey", alpha = 0.7) +
  #stat_summary(fun = median, geom = "crossbar", width = 0.4, color = "black", fatten = 1) +
  geom_point(stat = "summary", fun = median, shape = 18, size = 4, color = "black") +
  geom_text(aes(label = paste0("Median R²: ", round(..y.., 3))),
            stat = "summary", fun = median, vjust = -1, size = 4.5) +
  annotate("text", x = 1, y = 0.87, label = paste0(n_all, " proteins\n", format(n_var_all, big.mark = ","), " variants"), size = 4.5) +
  annotate("text", x = 2, y = 0.87, label = paste0(n_core, " proteins\n", format(n_var_core, big.mark = ","), " variants"), size = 4.5) +
  scale_y_continuous(limits = c(-0.1, 1), expand = c(0, 0.01)) +
  labs(
    title = "Human Proteome",
    subtitle = paste(n_all, "proteins"),
    x = NULL,
    y = expression("R² between ddGf and ESM1v pathogenicity")
  ) +
  scale_fill_manual(values = c("skyblue1", "steelblue3")) +
  theme_classic(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 13),
    legend.position = "none"
  )

ggsave("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/figs/panels/fig1_r2.pdf", plot = p10, width = 5, height = 4, dpi = 300)

p10
```

```{r, fig.width=10, fig.height=5}
protein_atlas_anno <- read.csv("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/data/proteome_meta/idmapping_gene_name.tsv")
nrow(protein_atlas_anno)

table(protein_atlas_anno$source_file)
#core_var_r2$protein_id <- sub("_filtered_with_esm1v\\.csv$", "", core_var_r2$protein_id)
#write.csv(core_var_r2, "/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/git_allostery_pathogenicity/data/proteome_meta/core_lm_r2.csv", row.names = FALSE)

core_var_r2_anno <- merge(core_var_r2, protein_atlas_anno, by.x="protein_id", by.y="uniprot", all.x = TRUE )
nrow(core_var_r2_anno)#35710<- same protein can be part of multiple groups 
length(unique(core_var_r2$protein_id)) #17420

core_var_r2_anno$source_file <- gsub("_", " ", core_var_r2_anno$source_file)

core_var_r2_anno <- core_var_r2_anno %>% filter(!is.na(source_file))
nrow(core_var_r2_anno) #35121

summary <- core_var_r2_anno %>%
  group_by(source_file) %>%
  summarise(
    count = n(),
    median_value = median(adj_r2)
  )

p11 <- ggplot(core_var_r2_anno, aes(
  x = source_file,
  y = adj_r2
)) +
  # Sample size annotation
  geom_text(
    data = summary, 
    aes(
      x = reorder(source_file, -median_value), 
      y = 0.8,
      label = paste0("n=", count)
    ), 
    size = 3.5, 
    color = "black"
  ) +
  # Violin plot with fixed color
  geom_violin(trim = FALSE, fill = "#0072B2", alpha = 0.7, color = NA) +  # All violins same color

  # Mean point
  stat_summary(
    fun = median, 
    geom = "point", 
    shape = 21, 
    size = 1, 
    color = "black", 
    fill = "black"
  ) +

  # Mean label
  stat_summary(
    fun = median, 
    geom = "text", 
    aes(label = round(..y.., 2)), 
    vjust = -0.5, 
    size = 3.5, 
    color = "black"
  ) +

  labs(
    title = "47,841,329 Variants (Protein Cores)",
    subtitle = "Protein cores excluding binding sites",
    x = "",
    y = "R²"
  ) +
  theme_classic() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 14, hjust = 0, face = "bold"),
    plot.subtitle = element_text(size = 14, hjust = 0),
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
    axis.title.y = element_text(size = 12),
    axis.line = element_line(size = 0.6)
  ) +
  ylim(-0.1, 1)

range(core_var_r2_anno$adj_r2) # -0.05881657  0.86482045

ggsave("/lustre/scratch126/gengen/projects_v2/alpha-allostery-global/allostery_pathogenicity/git_allostery_pathogenicity/figs/panels/fig1_r2_protein_type.pdf", plot = p11, width = 10, height = 5, dpi = 300)
p11
```
```{r}

```


```{r}

```




```{r}

```






